Repository TheGreatestYourManitto/TheGreatestYourManito-iOS, pull requests merged in 2024-11, with the labels that each got.

#13 [Feat/#10] CreateRoom_AfterWrite 화면, 액션 구현
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS.xcodeproj/project.pbxproj
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Application/Model/BottomSheetContentType.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Literal/StringLiterals.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ColorSet/lightError.colorset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_copy.imageset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_copy.imageset/link.svg
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_share.imageset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_share.imageset/link-external.svg
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ImageSet/check.imageset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ImageSet/check.imageset/Vector 76.png
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ImageSet/check.imageset/Vector 76@2x.png
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ImageSet/check.imageset/Vector 76@3x.png
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ImageSet/trash.imageset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ImageSet/trash.imageset/icon-trash.png
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ImageSet/trash.imageset/icon-trash@2x.png
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ImageSet/trash.imageset/icon-trash@3x.png
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Components/YMBottomSheet.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Components/YMCircleButton.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Components/YMJoinCodeStackView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/CreateRoom(After-Write)/CreateRoomView_AfterWrite.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/CreateRoom(After-Write)/CreateRoom_AfterWriteViewModel.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/CreateRoom(After-Write)/SubViews/CreateRoom_AfterWriteBottomView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/CreateRoom(After-Write)/SubViews/CreateRoom_AfterWriteTitleLabelView.swift
Labels: 🎨 Design, ✨ Feature

#12 Feat/#4 components
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS.xcodeproj/project.pbxproj
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_plus.imageset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_plus.imageset/icn_plus.svg
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_rightarrow.imageset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_rightarrow.imageset/icn_rightarrow.svg
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_setting.imageset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_setting.imageset/icn_setting.svg
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_smallLogo.imageset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_smallLogo.imageset/icn_smallLogo.svg
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Components/RoomCardView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Main/MainView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/SignUp/Views/SignUpView.swift
Labels: 🧹 Chore

#16 [Feat/#9] PlayAsManitto 재작성, PlayAsManittoResult 작성
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS.xcodeproj/project.pbxproj
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Application/Model/ManittoEventStatus.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Participate/PlayManitto/PlayManittoResultView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Participate/PlayManitto/PlayManittoView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Participate/PlayManitto/PlayManittoViewModel.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Participate/PlayManitto/SubView/PlayManittoBottomView.swift
Labels: 🎨 Design, ✨ Feature

#18 [Feat/#15] MainViewUI 수정 반영
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_check_circle.imageset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_check_circle.imageset/icnCheckCircle.svg
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_plus_circle.imageset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/IconSet/icn_plus_circle.imageset/icnPlusCircle.svg
Labels: ✨ Feature

#19 [Feat] 방 입장 전, 이후, 입장 로딩 뷰 구현
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS.xcodeproj/project.pbxproj
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Application/Model/BottomSheetContentType.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Literal/StringLiterals.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/AfterJoinRoom/AfterJoinRoomView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/AfterJoinRoom/JoinMemberModel.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/AfterJoinRoom/SubViews/AfterJoinRoomBottomView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/BeforeJoinRoom/BeforeJoinRoomView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/BeforeJoinRoom/SubViews/BeforeJoinRoomBottomView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Components/ActivityViewController.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Components/YMJoinCodeStackView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Components/YMLoadingView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Components/YMNavigationBar.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/CreateRoom(After-Write)/CreateRoomView_AfterWrite.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/CreateRoom(After-Write)/SubViews/CreateRoom_AfterWriteBottomView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/CreateRoom(After-Write)/SubViews/CreateRoom_AfterWriteTitleLabelView.swift
Labels: 🎨 Design, ✨ Feature

#26 [Docs/#25] .gitignore 수정
  .gitignore
Labels: 📃 Docs

#27 [Feat] 네트워크 통신 세팅
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS.xcodeproj/project.pbxproj
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Info.plist
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Base/BaseService.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Base/BaseTargetType.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Base/MoyaLoggingPlugin.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Base/NetworkResult.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Base/NetworkService.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Config/Config.swift
Labels: ⚙️ Setting, ✨ Feature

#29 [Hotfix/#28] judgeStatus 에러 범위 수정
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Base/BaseService.swift
Labels: 🔥 HotFix

#32 [Feat] JoinRoom(Before, After) ViewModel 적용 및 Network User 구현 및 API 연결 등
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS.xcodeproj/project.pbxproj
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Application/Model/RoomType.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Utility/Device.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Base/BaseResponseBody.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Base/BaseService.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Base/NetworkService.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Cheer/CheerService.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Cheer/CheerTargetType.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Room/RoomService.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Room/RoomTargetType.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/User/RequestDTO/MakeUserRequestBody.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/User/RequestDTO/UserIdentifyRequestBody.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/User/ResponseDTO/UserCodeResponseBody.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/User/UserService.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/User/UserTargetType.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/AfterJoinRoom/AfterJoinRoomView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/AfterJoinRoom/SubViews/AfterJoinRoomBottomView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/BeforeJoinRoom/BeforeJoinRoomView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/BeforeJoinRoom/JoinRoomViewModel.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/BeforeJoinRoom/SubViews/BeforeJoinRoomBottomView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Intro/IntroView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Intro/IntroViewModel.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/SignUp/Views/SignUpView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/SignUp/Views/SignUpViewModel.swift
Labels: ✨ Feature, 📬 API

#37 [Feat] JoinRoom 관련 API 연결
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS.xcodeproj/project.pbxproj
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Base/BaseHeader.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Base/NetworkService.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Room/RequestDTO/ParticipateRoomRequestBody.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Room/ResponseDTO/ParticipateRoomResponseBody.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Room/ResponseDTO/RoomInfoResponseBody.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Room/RoomService.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/Room/RoomTargetType.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/User/ResponseDTO/UserCodeResponseBody.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Network/User/UserService.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/AfterJoinRoom/AfterJoinRoomView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/AfterJoinRoom/JoinMemberModel.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/AfterJoinRoom/SubViews/AfterJoinRoomBottomView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/BeforeJoinRoom/JoinRoomViewModel.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/BeforeJoinRoom/SubViews/BeforeJoinRoomBottomView.swift
Labels: ✨ Feature, 📬 API
