Repository TheGreatestYourManitto/TheGreatestYourManito-iOS, pull requests merged in 2024-10, with the labels that each got.

#3 Setting/#1 project setting
  .gitignore
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS.xcodeproj/project.pbxproj
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ColorSet/ym_black.colorset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ColorSet/ym_blue.colorset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ColorSet/ym_green.colorset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ColorSet/ym_pink.colorset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ColorSet/ym_primary.colorset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ColorSet/ym_white.colorset/Contents.json
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Resource/Assets.xcassets/ColorSet/ym_yellow.colorset/Contents.json
Labels: 🐞 BugFix

#5 [Chore/#4] components 생성
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS.xcodeproj/project.pbxproj
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Application/TheGreatestYourManito_iOSApp.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Extension/Font+.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Info.plist
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Components/YMButton.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Components/YMTextField.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Intro/IntroView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/SignUp/Views/SignUpView.swift
Labels: 🧹 Chore

#8 [Setting/#7] apply missing settings
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS.xcodeproj/project.pbxproj
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: ⚙️ Setting

#11 [Feat/#9] PlayAsManitto 화면, 로직 작성
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS.xcodeproj/project.pbxproj
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Application/Model/CheerType.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Application/Model/ManittoEventStatus.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Extension/View+.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Global/Utility/roundCorner.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Components/YMCapsuleLabel.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Components/YMNavigationBar.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Participate/PlayManitto/PlayManittoView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Participate/PlayManitto/PlayManittoViewModel.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Participate/PlayManitto/SubView/NameTagView.swift
  TheGreatestYourManito-iOS/TheGreatestYourManito-iOS/Presentation/Participate/PlayManitto/SubView/PlayManittoBottomView.swift
Labels: 🎨 Design, ✨ Feature
